# Example CI/CD script with TLS disabled
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build -t ashantharaka/flask-ci-cd-example:latest .

      - name: Push the Docker image
        run: docker push ashantharaka/flask-ci-cd-example:latest

      - name: Deploy the container
        env:
          DOCKER_HOST: tcp://192.168.8.100:2375
          # TLS-related variables are removed
        run: |
          docker stop flask-ci-cd || true
          docker rm flask-ci-cd || true
          docker run -d -p 5000:5000 --name flask-ci-cd ashantharaka/flask-ci-cd-example:latest
