name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: pytest

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ashantharaka/flask-ci-cd-example:latest

    - name: Deploy Container to Remote Server
      env:
        DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
        DOCKER_CERT_PATH: ${{ secrets.DOCKER_CERT_PATH }}
        DOCKER_TLS_VERIFY: 0
      run: |
        docker pull ashantharaka/flask-ci-cd-example:latest
        docker stop flask-ci-cd || true
        docker rm flask-ci-cd || true
        docker run -d -p 5000:5000 --name flask-ci-cd ashantharaka/flask-ci-cd-example:latest
